In [1]:
from sklearn.preprocessing import LabelEncoder

data = ['cat', 'dog', 'fish', 'cat', 'bird', 'dog', 'bird']

encoder = LabelEncoder()
encoded_data = encoder.fit_transform(data)
print(encoded_data)

[1 2 3 1 0 2 0]


In [6]:
encoder.inverse_transform([2])

array(['dog'], dtype='<U4')

In [12]:
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([[2.0, 5.0],
                [4.0, 8.0],
                [6.0, 12.0]])

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print("Original data: ", data)
print()
print("Scaled data: ", scaled_data)

Original data:  [[ 2.  5.]
 [ 4.  8.]
 [ 6. 12.]]

Scaled data:  [[-1.22474487 -1.16247639]
 [ 0.         -0.11624764]
 [ 1.22474487  1.27872403]]


In [16]:
from sklearn.preprocessing import PolynomialFeatures

data = [[1,3],
        [2,4]]

pf1 = PolynomialFeatures(degree=3, interaction_only=True)
pf2 = PolynomialFeatures(degree=3, interaction_only=False)
print(pf1.fit_transform(data))
print()
print(pf2.fit_transform(data))

[[1. 1. 3. 3.]
 [1. 2. 4. 8.]]

[[ 1.  1.  3.  1.  3.  9.  1.  3.  9. 27.]
 [ 1.  2.  4.  4.  8. 16.  8. 16. 32. 64.]]


---

In [23]:
from sklearn.linear_model import Perceptron
X = [[0,0], [0,1], [1,0], [1,1]]
y = [0,0,0,1]

clf = Perceptron(tol=None, shuffle=False)
clf.fit(X, y)

print(clf.predict([[1,1]]))

[1]


In [27]:
from sklearn.naive_bayes import GaussianNB

X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
Y = np.array([1, 1, 1, 2, 2, 2])

clf = GaussianNB()
clf.fit(X, Y)

data = np.array([[-0.8, -1]])
print(clf.predict(data))

clf_pf = GaussianNB()
clf_pf.partial_fit(X, Y, np.unique(Y))

new_data = np.array([[-0.8, -1]])
print(clf_pf.predict(new_data))

[1]
[1]


In [30]:
from sklearn.neighbors import KNeighborsClassifier

X = [[2,3], [5,6], [10,11], [15,16], [20,21]]
y = [0, 1, 1, 1, 2]

knn = KNeighborsClassifier(n_neighbors=3,
                           metric="euclidean",
                           weights="uniform")

knn.fit(X, y)
print(knn.predict([[8,9]]))

[1]


In [33]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = ["Bias is actually the error rate of the training data",
          "The difference between train and test error is called variance."]

vectorizer = CountVectorizer()
vectors = vectorizer.fit_transform(corpus)
print(vectors.shape)

(2, 16)


In [35]:
from sklearn.cluster import KMeans

data = np.array([[150,6], [300,12], [50,2], [250,8], [80,3]])

kmeans = KMeans(n_clusters=3)
kmeans.fit(data)

labels = kmeans.labels_
centroids = kmeans.cluster_centers_

print("Labels: ", labels)
print("Centroids: ", centroids)

Labels:  [2 1 0 1 0]
Centroids:  [[ 65.    2.5]
 [275.   10. ]
 [150.    6. ]]


In [2]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names_out()

array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
       'this'], dtype=object)

In [4]:
X.shape

(4, 9)