NumPy - Numerical Python

Advantages of Numpy Arrays:
1. Allows several mathematical operations
2. Faster operations

In [ ]:
import numpy as np

List Vs Numpy - Time Taken

In [ ]:
from time import process_time

Time taken by a list

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()

print((end_time - start_time)*1000, "milliseconds")

1.2888819999998802 milliseconds


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()
np_array += 5
end_time = process_time()

print((end_time - start_time)*1000, "milliseconds")

0.1781330000003578 milliseconds


Numpy Arrays

In [ ]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
# creating a 1 dim array
a = np.array([1,2,3,4])
a.shape

(4,)

In [ ]:
# creating a 2 dim array
b = np.array([(1,2,3,4), (5,6,7,8)])
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4), (5,6,7,8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial placeholders in numpy array

In [ ]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy array of Ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
# array of a particular value
z = np.full((5,4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [24]:
# create an identity matrix
a = np.eye(4, dtype=int)
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [26]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.21761157 0.16178159 0.15159507 0.38696678]
 [0.44097597 0.91304539 0.328312   0.89033651]
 [0.3597232  0.40390169 0.05054362 0.20613887]]


In [27]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[97 42 65 99 76]
 [61 97 10 24 51]
 [76 36 44 23 34]]


In [34]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,6, dtype=int)
print(d)

[10 14 18 22 26 30]


In [35]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,6)
print(e)

[10 16 22 28]


In [37]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)

[10 20 20 20 50]


Analyzing a numpy array

In [38]:
c = np.random.randint(10,90,(5,5))
print(c)

[[30 14 48 42 45]
 [59 74 77 77 81]
 [53 40 47 32 23]
 [81 87 10 71 57]
 [32 15 66 33 63]]


In [39]:
# array dimension
print(c.shape)

(5, 5)


In [40]:
# number of dimensions
print(c.ndim)

2


In [42]:
# number of elements in an array
print(c.size)

25


In [43]:
# checking the data type of values in the array
print(c.dtype)

int64


Mathematical Operations on NumPy array

In [45]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2) # concatenates two lists

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [50]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[5 7 4]
 [2 8 9]
 [8 4 3]]
[[14 18 16]
 [16 19 13]
 [15 15 17]]


numpy.ndarray

In [52]:
print(a+b) # adds the elements in case of numpy ndarray
print(a-b)
print(a*b)
print(a/b)

[[19 25 20]
 [18 27 22]
 [23 19 20]]
[[ -9 -11 -12]
 [-14 -11  -4]
 [ -7 -11 -14]]
[[ 70 126  64]
 [ 32 152 117]
 [120  60  51]]
[[0.35714286 0.38888889 0.25      ]
 [0.125      0.42105263 0.69230769]
 [0.53333333 0.26666667 0.17647059]]


In [53]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [57]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[17 12 20]
 [18 19 16]
 [17 23 19]]
[[ -7  -8 -16]
 [-16 -15 -14]
 [-13  -7  -9]]
[[ 60  20  36]
 [ 17  34  15]
 [ 30 120  70]]
[[0.41666667 0.2        0.11111111]
 [0.05882353 0.11764706 0.06666667]
 [0.13333333 0.53333333 0.35714286]]


Array Manipulation

In [58]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 4 3]
 [1 7 1]]
(2, 3)


In [59]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[2 1]
 [4 7]
 [3 1]]
(3, 2)


In [60]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 8 7]
 [1 5 7]]
(2, 3)


In [62]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[9 1]
 [8 5]
 [7 7]]
(3, 2)


In [63]:
# reshape a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[8 3 5]
 [3 9 1]]
(2, 3)


In [66]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[8 3]
 [5 3]
 [9 1]]
(3, 2)
